apiVersion: v1
kind: Pod
metadata:
  name: mypod1
  labels:
    role: myrole
spec:
  containers:
    - name: mycontainer
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
EOF